// Generated by `flutterfire configure` for Firebase project metermind-f26fb.
// (An Android Firebase API key is not a secret — it ships in the app — but avoid
// committing this to a PUBLIC repo. Re-run `flutterfire configure` to refresh.)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv34UV17hme6GY37AhzLqhQg8qRtpsb0I',
    appId: '1:1077084238541:android:ae73a8f93c5868097b6f84',
    messagingSenderId: '1077084238541',
    projectId: 'metermind-f26fb',
    storageBucket: 'metermind-f26fb.firebasestorage.app',
  );
}
